// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import repository "github.com/eggsbenjamin/piemapping/repository"

// Queryer is an autogenerated mock type for the Queryer type
type Queryer struct {
	mock.Mock
}

// Query provides a mock function with given fields: _a0, _a1
func (_m *Queryer) Query(_a0 string, _a1 ...interface{}) (repository.RowIterator, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	var r0 repository.RowIterator
	if rf, ok := ret.Get(0).(func(string, ...interface{}) repository.RowIterator); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.RowIterator)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
